name: jupyterlab-blockly-docs

channels:
  - conda-forge

dependencies:
  - mamba
  - myst-parser
  - pydata-sphinx-theme
  - pip:
    - jupyterlab-blockly
    - jupyterlite-core
    - jupyterlite-sphinx
    - jupyterlite-xeus
