name: jupyterlab-blockly-docs

channels:
  - conda-forge

dependencies:
  - mamba
  - myst-parser
  - pydata-sphinx-theme
  - python
  - jupyerlab-blockly
  - pip:
    # Remove all pinning when we support jupyterlab v4 in jupyterlab-blockly
    - jupyterlite-core
    - jupyterlite-sphinx
    - jupyterlite-xeus
