name: jupyterlab-blockly-docs

channels:
  - conda-forge

dependencies:
  - mamba
  - myst-parser
  - pydata-sphinx-theme
  - python=3.9
  - pip:
    - jupyterlab-blockly
    # Remove these pins when we support jupyterlab v4 in jupyterlab-blockly
    - jupyterlite-core===0.1.3
    - jupyterlite-sphinx===0.9.3
    - jupyterlite-xeus===0.1.8
