name: jupyterlab-blockly-docs

channels:
  - conda-forge

dependencies:
  - mamba
  - myst-parser
  - pydata-sphinx-theme
  - python=3.9
  - pip:
    - jupyterlab-blockly
    - jupyterlite-core===0.1.2
    - jupyterlite-sphinx
    - jupyterlite-xeus
