name: jupyterlab-blockly-docs

channels:
  - conda-forge

dependencies:
  - python=3.9
  - mamba
  - myst-parser
  - pydata-sphinx-theme
  - jupyterlab
  - yarn
  - pip:
    - ..
    - jupyterlite-core
    - jupyterlite-sphinx
    - jupyterlite-xeus
